<script>
require(['jquery'], function($) {
    $(document).ready(function() {
        var clientId = "<?= $block->escapeJs($block->getClientId()) ?>"; // Fetch the client ID safely

        function initializeGSSDK() {
            var contextData = {};
            var pageType = "";
            var cartItems = <?= json_encode($block->getCartItems()) ?>;  // Get cart items as JSON

            if ("<?= $block->isHomePage() ?>") {
                pageType = 'home';
                contextData = { pageType: pageType };
            } else if ("<?= $block->isProductPage() ?>") {
                pageType = 'product_detail';
                var productId = "<?= $block->getCurrentProductId() ?>";
                contextData = { pageType: pageType, product_id: productId };
            } else if ("<?= $block->isCartPage() ?>") {
                pageType = 'cart';
                contextData = { pageType: pageType, cart_items};
            } else if ("<?= $block->isCheckoutPage() ?>") {
                pageType = 'checkout';
                contextData = { pageType: pageType, cart_items};
            }

            window.gsSDK = new window.GSSDK.default(clientId, {
                provider: 'Magento_V2',
                context: contextData
            });
        }

        var gsSDKScript = document.createElement('script');
        gsSDKScript.src = 'https://sdk.gopersonal.ai/gs-sdk.js';
        gsSDKScript.onload = initializeGSSDK;
        document.head.appendChild(gsSDKScript);
    });
});
</script>
