<!-- console_log.phtml -->
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            var clientId = "<?= $block->escapeJs($block->getClientId()) ?>"; // Use escapeJs for security
            console.log("Client ID:", clientId); // Logs the Client ID to the console
            console.log("This is a console log from the Gopersonal_Magento module.");
        });
    });
</script>
