<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\LayeredNavigation\ViewModel\Layer\Filter;

/** @var \Magento\LayeredNavigation\Block\Navigation\FilterRenderer $block */
/** @var Escaper $escaper */
/** @var Filter $viewModel */

$viewModel = $block->getData('product_layer_view_model');
$mageVersion = $block->getVersion();
$filterCounts = $block->getData('filter_counts'); // Get custom filter counts
$filter = $block->getData('filter'); // Get the filter object

// Initialize locale formatter if needed (Magento 2.4.5+)
$localeFormatter = null;
if (version_compare($mageVersion, "2.4.5", '>')) {
    $localeFormatter = $block->getLocaleFormatter();
}

?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
        $filterCount = 0;
        if (isset($filterCounts[$block->escapeHtml($filter->getRequestVar())][$filterItem->getValue()])) { // Get current filter
            $filterCount = $filterCounts[$block->escapeHtml($filter->getRequestVar())][$filterItem->getValue()];
        }
        ?>
        <li class="item">
            <?php if ($filterCount > 0): ?>
                <a href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>" rel="nofollow">
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($viewModel->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count">
                            <?php if ($localeFormatter): ?>
                                <?= $escaper->escapeHtml($localeFormatter->formatNumber($filterCount)) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($filterCount) ?>
                            <?php endif; ?>
                            <span class="filter-count-label">
                                <?= $escaper->escapeHtml(__($filterCount == 1 ? 'item' : 'items')) ?>
                            </span>
                        </span>
                    <?php endif; ?>
                </a>
            <?php else: ?>
                <span class="item-label"><?= /* @noEscape */ $filterItem->getLabel() ?></span> 
                <?php if ($viewModel->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count">
                        <?php if ($localeFormatter): ?>
                            <?= $escaper->escapeHtml($localeFormatter->formatNumber($filterCount)) ?>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($filterCount) ?>
                        <?php endif; ?>
                        <span class="filter-count-label">
                            <?= $escaper->escapeHtml(__('items')) ?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ol>